# Generated by Django 5.1 on 2024-09-04 15:47

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_reviews_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color_hex', models.CharField(help_text='Введите цвет в формате #RRGGBB', max_length=7, validators=[api.models.validate_hex_color])),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='tags',
            field=models.ManyToManyField(related_name='doors', to='api.tag'),
        ),
    ]
