# Generated by Django 5.1 on 2024-09-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='reviews',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='api.review'),
            preserve_default=False,
        ),
    ]
