# Generated by Django 5.1 on 2024-09-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_door_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='api.door'),
        ),
    ]
