# Generated by Django 5.1 on 2024-09-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_review_order_number_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='door',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='api.door'),
            preserve_default=False,
        ),
    ]
