# Generated by Django 5.1 on 2024-09-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_order_door'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='reviews',
        ),
    ]
