# Generated by Django 5.1 on 2024-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('conturs_name', models.CharField(max_length=255)),
                ('size_name', models.CharField(max_length=255)),
                ('steel_size', models.CharField(max_length=255)),
                ('tolshina', models.CharField(max_length=255)),
                ('korob_size', models.CharField(max_length=255)),
                ('uteplitel', models.CharField(max_length=255)),
                ('ves', models.CharField(max_length=255)),
                ('constr_korob', models.CharField(max_length=255)),
                ('constr_fixator', models.CharField(max_length=255)),
                ('zamok1', models.CharField(max_length=255)),
                ('zamok2', models.CharField(max_length=255)),
                ('furn_color_name', models.CharField(max_length=255)),
                ('petli', models.CharField(max_length=255)),
                ('zadvijka', models.CharField(max_length=255)),
                ('ruchka', models.CharField(max_length=255)),
                ('glazok', models.CharField(max_length=255)),
                ('cilindr', models.CharField(max_length=255)),
                ('bronia', models.CharField(max_length=255)),
                ('out_cover_name', models.CharField(max_length=255)),
                ('out_color', models.CharField(max_length=255)),
                ('in_cover_name', models.CharField(max_length=255)),
                ('in_thick', models.CharField(max_length=255)),
                ('in_color', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('discount', models.PositiveSmallIntegerField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('message', models.TextField()),
                ('order_number', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
