# Generated by Django 5.1 on 2024-09-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
