# Generated by Django 5.1 on 2024-09-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_equipment_alter_door_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
