# Generated by Django 5.1 on 2024-09-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_door_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='api.review'),
        ),
    ]
