# Generated by Django 5.1 on 2024-09-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_door'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_number',
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.order'),
            preserve_default=False,
        ),
    ]
