# Generated by Django 5.0 on 2024-09-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('conturs_name', models.CharField(max_length=255)),
                ('size_name', models.CharField(max_length=255)),
                ('steel_size', models.CharField(max_length=255)),
                ('tolshina', models.CharField(max_length=255)),
                ('korob_size', models.CharField(max_length=255)),
                ('uteplitel', models.CharField(max_length=255)),
                ('ves', models.CharField(max_length=255)),
                ('constr_korob', models.CharField(max_length=255)),
                ('constr_fixator', models.CharField(max_length=255)),
                ('zamok1', models.CharField(max_length=255)),
                ('zamok2', models.CharField(max_length=255)),
                ('furn_color_name', models.CharField(max_length=255)),
                ('petli', models.CharField(max_length=255)),
                ('zadvijka', models.CharField(max_length=255)),
                ('ruchka', models.CharField(max_length=255)),
                ('glazok', models.CharField(max_length=255)),
                ('cilindr', models.CharField(max_length=255)),
                ('bronia', models.CharField(max_length=255)),
                ('out_cover_name', models.CharField(max_length=255)),
                ('out_color', models.CharField(max_length=255)),
                ('in_cover_name', models.CharField(max_length=255)),
                ('in_thick', models.CharField(max_length=255)),
                ('in_color', models.CharField(max_length=255)),
                ('images', models.TextField()),
                ('discount', models.PositiveSmallIntegerField(default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(help_text='Введите цвет в формате #RRGGBB', max_length=7)),
                ('in_cloud', models.BooleanField(verbose_name='Добавление тэга в каталог категорий')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField()),
                ('address', models.TextField()),
                ('message', models.TextField()),
                ('order_number', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='web.door')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('message', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='web.order')),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='doors', to='web.tag'),
        ),
    ]
