# Generated by Django 5.0 on 2024-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_color_tag_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='Choose text color', max_length=10),
        ),
    ]
