# Generated by Django 5.0 on 2024-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_door_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='discount',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
