# Generated by Django 5.0 on 2024-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tag_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
