# Generated by Django 5.0 on 2024-09-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_door_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
