# Generated by Django 5.0 on 2024-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_door_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='price',
            field=models.IntegerField(),
        ),
    ]
