# Generated by Django 5.0 on 2024-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_catalog_alter_tag_in_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='catalogs',
            field=models.ManyToManyField(blank=True, related_name='catalogs', to='web.catalog'),
        ),
    ]
