# Generated by Django 5.0 on 2024-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
