# Generated by Django 5.0 on 2024-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_blogchapter_alter_deliveryregion_image_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
