# Generated by Django 5.0 on 2024-09-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_blogchapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogchapter',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
