# Generated by Django 5.0 on 2024-09-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_blogchapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogchapter',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
