# Generated by Django 5.0 on 2024-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_blogchapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
