# Generated by Django 5.0 on 2024-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryregion',
            name='region',
            field=models.CharField(choices=[('moscow', 'Москва'), ('moscow_region', 'Московская область')], default='moscow', max_length=20, verbose_name='Регион'),
        ),
    ]
