# Generated by Django 5.0 on 2024-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_deliveryregion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryregion',
            name='cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='image',
            field=models.ImageField(blank=True, upload_to='delivery_region'),
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
