# Generated by Django 5.0 on 2024-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_deliveryregion_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryregion',
            name='d',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryregion',
            name='fill',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryregion',
            name='region',
            field=models.CharField(choices=[('moscow', 'Москва'), ('moscow_region', 'Московская область')], default='moscow_region', max_length=20, verbose_name='Регион'),
        ),
    ]
