# Generated by Django 5.0 on 2024-09-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_deliveryregion_d_deliveryregion_fill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryregion',
            name='d',
        ),
        migrations.RemoveField(
            model_name='deliveryregion',
            name='fill',
        ),
    ]
