# Generated by Django 5.0 on 2024-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_equipment_door_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='equipment',
        ),
        migrations.AddField(
            model_name='door',
            name='equipment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
