# Generated by Django 5.0 on 2024-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_remove_door_equipment_door_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='equipment',
            field=models.CharField(max_length=1048576),
        ),
    ]
