# Generated by Django 5.0 on 2024-09-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_review_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
