# Generated by Django 5.0 on 2024-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default=1, upload_to='catalog'),
            preserve_default=False,
        ),
    ]
