# Generated by Django 5.0 on 2024-09-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_catalog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog'),
        ),
    ]
