# Generated by Django 5.0 on 2024-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_customorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
    ]
