# Generated by Django 5.0 on 2024-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_getdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='in_cloud',
            field=models.BooleanField(default=False, verbose_name='Добавление каталога в облако (каталог)'),
            preserve_default=False,
        ),
    ]
