# Generated by Django 5.0 on 2024-10-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_catalog_in_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='in_cloud',
        ),
    ]
