# Generated by Django 5.0 on 2024-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_remove_tag_in_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='description',
            field=models.CharField(default='Купить дверь <django.db.models.fields.CharField>, недорого', max_length=255),
        ),
    ]
