# Generated by Django 5.0 on 2024-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_door_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='catalogs_cloud',
            field=models.ManyToManyField(blank=True, related_name='catalogs_cloud', to='web.catalog'),
        ),
    ]
