# Generated by Django 5.0 on 2024-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
