# Generated by Django 5.0 on 2024-10-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_door_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
