# Generated by Django 5.0 on 2024-10-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_alter_catalog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
