# Generated by Django 5.0 on 2024-10-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
