# Generated by Django 5.0 on 2024-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_alter_review_message_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
