# Generated by Django 5.0 on 2024-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_door_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
