# Generated by Django 5.0 on 2024-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_door_h1_alter_door_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='custom_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
